#!/usr/bin/env python

import argparse
import Nio
import numpy as np

def rmse(var1, var2):
    return np.sqrt(((var1 - var2) ** 2).mean())

def abs_diff(var1, var2):
    return (np.absolute(var1 - var2)).mean()

parser = argparse.ArgumentParser()
parser.add_argument("file1")
parser.add_argument("file2")
args = parser.parse_args()

file1 = Nio.open_file(args.file1)
file2 = Nio.open_file(args.file2)

print(file1.variables.keys())

for varname in sorted(file1.variables.keys()):
    if (file1.variables[varname].typecode()[0] == 'S'):
        continue
    var1 = file1.variables[varname].get_value()
    var2 = file2.variables[varname].get_value()
    this_rmse = rmse(var1, var2)
    print("{var}: {rmse}".format(var=varname, rmse=this_rmse))
    this_abs_diff = abs_diff(var1, var2)
    print("{var}: {abs_diff}".format(var=varname, abs_diff=this_abs_diff))


          
    
